### ISSUE TITLE
Bug: Feedback Page Input Sanitization

### ISSUE THREAD

**Issue by joshmfrancis** [Project-AirStorm/Airstorm-GFS#114]
# [Bug] Feedback Page Input Sanitization
Description: Fix input sanitization issues in feedback form
## Environment
- Branch: main
- OS: All
- Browser: All
## Steps to Reproduce
1. Go to feedback page
2. Enter text with quotes (', ", '', "")
3. Submit feedback
4. Check yml workflow files
## Expected Behavior
Quotes should be properly escaped in the workflow files.
## Actual Behavior
Quotes cause formatting issues in yml files.
## Code Causing Error
```yaml
name: Process Feedback
on:
  workflow_dispatch:
    inputs:
      feedback:
        description: 'User feedback'
        required: true
```
## Code for Fix
```javascript
const sanitizeFeedback = (input) => {
  return input
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .trim();
};

const handleSubmit = (feedback) => {
  const sanitizedFeedback = sanitizeFeedback(feedback);
  // Submit sanitized feedback
};
```
## Additional Context
Considered implementing server-side validation as well, didn't want to implement this, though, it's difficult.
