### ISSUE TITLE
Feature: Release Notes Generator

### ISSUE THREAD

**Issue by joshmfrancis** [Project-AirStorm/Airstorm-GFS#91]
# Feature: Release Notes Generator

## Description
This action automatically generates comprehensive release notes by analyzing commits between releases. It categorizes changes by frontend and backend components, and further organizes them into features, improvements, and bug fixes.

## Environment
- Branch: `main` (triggered on merge from `dev`)
- OS: Cross-platform
- CI/CD: GitHub Actions
- API: Google Gemini

## Request
The automated system performs the following tasks:
1. Detects pushes to the main branch
2. Increments version numbers (0.1 → 0.2 → 0.3, etc.)
3. Collects commit history since last release
4. Generates AI-powered release notes using Gemini
5. Creates GitHub releases with formatted notes

## Code Related to Request
```yaml
name: Build, Release and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  actions: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
          repository: Project-AirStorm/Airstorm-GFS
          
      - name: Get latest version
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0")
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          
      - name: Bump version
        id: bump_version
        run: |
          CURRENT_VERSION=${LATEST_TAG#v}
          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          MINOR=$((${version_parts[1]} + 1))
          NEW_VERSION="0.${MINOR}"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "v${NEW_VERSION}" -m "Release version ${NEW_VERSION}"
          git push origin "v${NEW_VERSION}"
  generate-notes:
    needs: version-bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
          repository: Project-AirStorm/Airstorm-GFS
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Get commit messages
        id: get_commits
        env:
          GITHUB_TOKEN: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
        run: |
          # Get the latest merge commit from dev to main
          LATEST_MERGE=$(git log --merges --first-parent main --grep="Merge.*dev" -n 1 --format="%H")
          
          # Get the previous merge commit from dev to main
          PREVIOUS_MERGE=$(git log --merges --first-parent main --grep="Merge.*dev" -n 2 --format="%H" | tail -n 1)
          
          if [ -z "$PREVIOUS_MERGE" ]; then
            echo "No previous merge found, getting all commits up to latest merge"
            echo "Changes since repository creation up to latest merge:" > changes.txt
            git log --format="%h %s" $LATEST_MERGE > changes.txt
          else
            echo "Getting changes between $PREVIOUS_MERGE and $LATEST_MERGE"
            echo "Changes since last dev merge:" > changes.txt
            git log --format="%h %s" $PREVIOUS_MERGE..$LATEST_MERGE > changes.txt
          fi
          
          # Debug output
          echo "Latest merge commit: $LATEST_MERGE"
          echo "Previous merge commit: $PREVIOUS_MERGE"
          echo "Content of changes.txt:"
          cat changes.txt
          
          # Escape content for JSON
          CHANGES=$(cat changes.txt | jq -sRr @json)
          echo "changes=${CHANGES}" >> $GITHUB_OUTPUT
      - name: Generate release notes
        id: generate_notes
        uses: actions/github-script@v6
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          COMMITS: ${{ steps.get_commits.outputs.changes }}
          NEW_VERSION: ${{ needs.version-bump.outputs.new_version }}
        with:
          script: |
            const axios = require('axios');
            
            const prompt = `As a technical writer, create professional release notes from these git commits.
            Format the output in the following structure:
            
            # Release v${process.env.NEW_VERSION}
            
            ## 🔄 Changes
            
            ${process.env.COMMITS}
            
            Please categorize the changes into:
            - 🚀 New Features
            - 🔨 Improvements
            - 🐛 Bug Fixes
            
            Use clear, concise language and proper markdown formatting.
            Include the commit hash in parentheses after each item.
            Skip any commits that are purely administrative (like merge commits).`;
            
            try {
              const response = await axios.post('https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent', {
                contents: [{
                  parts: [{
                    text: prompt
                  }]
                }],
                generationConfig: {
                  maxOutputTokens: 1024,
                  temperature: 0.7,
                  topK: 40,
                  topP: 0.95
                }
              }, {
                headers: {
                  'Content-Type': 'application/json',
                  'x-goog-api-key': process.env.GEMINI_API_KEY
                }
              });
              
              if (!response.data.candidates || !response.data.candidates[0]) {
                throw new Error('No response from Gemini API');
              }
              
              const releaseNotes = response.data.candidates[0].content.parts[0].text;
              core.setOutput('notes', releaseNotes);
              
              // Debug output
              console.log('Generated Release Notes:');
              console.log(releaseNotes);
            } catch (error) {
              core.setFailed(`Error generating release notes: ${error.message}`);
              throw error;
            }
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.version-bump.outputs.new_version }}
          name: Release v${{ needs.version-bump.outputs.new_version }}
          body: ${{ steps.generate_notes.outputs.notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.BACKEND_GITHUB_ACCESS_TOKEN }}
```

## Additional Context
- The release notes are generated using Google's Gemini AI model for natural language processing
- The system maintains semantic versioning while keeping the major version at 0
- Release notes are automatically formatted in Markdown for better readability
- The system handles both frontend and backend changes in a single release document
- All security-sensitive information (API keys) is stored in GitHub Secrets
